### ISSUE TITLE
Apply Now Button Enhancement

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#112]
Change "Contact" button in top bar menu to "Apply Now" and make it link to: https://seattleu.secure.force.com/form?formid=217882

Change Apply Now link in megamenu to point to: https://seattleu.secure.force.com/form?formid=217882

Anywhere else on the site where "Apply Now" is linked it should link to: https://seattleu.secure.force.com/form?formid=217882

**Comment by jfehrenbacher** [comment]
Contact Button can't be changed to "Apply Now" button. The only buttons that the theme allows to exist in the Top Bar are 'Login' and 'Contact' buttons. Instead I added a custom link to the 'Topbar Menu'. Unfortunately, I think due to the SEATTLEU logo link that we added, the 'Apply Now' link is displaced a bit. I went into the style.css file and added the following code:

`.top-links a[href="https://seattleu.secure.force.com/form?formid=217882"] {
    position:relative;
    bottom:20px;
}`

Committed and pushed, only needs to be pulled over by Shawn now.
