### ISSUE TITLE
Student Success Section

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#15]
Provide content for the Student Success section and subsections defined in the NCS Website IA.

**Comment by shawnr** [comment]
Web Dev Portfolios: https://gist.github.com/shawnr/497cd3f55e2114cb2279

**Comment by reiners** [comment]
Spring Break might hinder my getting this done by Friday, but we'll see! :)

**Comment by reiners** [comment]
I haven't heard back from Wanda yet, but Viv had this to say and I imagine, Wanda feels similarly: 
"Hi Sara, 

I wish I had something to provide you for the site, but although we have had students change or start new jobs since they started a year ago, I can't think of anything tangible for you to include. I know we will have some good stories, but right now, they are probably still percolating... Maybe next time?? 

Viviane"
