### ISSUE TITLE
Review, develop, fine tune content for Information Center

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#32]
Sara will convene a meeting with Trish and Suki to determine the content for the Info Center section to best serve current students.

**Comment by reiners** [comment]
Hi Team,
I met with Suki and Trish today and we discussed what we would like to see under Info Center as far as organization: 
[Info Center.docx](https://github.com/suwebdev/ncs-michigan/files/873764/Info.Center.docx)

Note, the highlighted section is a technical question, as to how we can pull in a scheduling feature for advising appointments. 

I am meeting with Suki and Trish next week to go over content for this section in more detail and will have an update for the following Friday meeting. 
Thanks! :)
Sara

**Comment by reiners** [comment]
Trish, Suki and I met this week to fine tune the content we would like to see in the Information Center. We have agreed to assign the following people the following content and are meeting again, including Rick, to go over content on April 25th.

Advising Center:
1.  Meet Your Professional Advisor (Suki Bio and Image) **See new image attached**
![suki](https://cloud.githubusercontent.com/assets/25487538/25153572/dbcc7ce6-2441-11e7-9efa-35d31ddfdead.png)

Please use this updated bio: 
Your academic adviser serves as a primary source of guidance as you navigate your undergraduate or certificate requirements.  Communicate with your adviser early, and often!
 
Hello, my name is Suki Kwon, and I am thrilled to be your advisor. I graduated from Oregon State University with a B.A. in English Literature and an M.Ed. in College Student Services Administration.  I am passionate about adult learning and love helping students achieve their personal and professional goals. Returning to school can be intimidating for many people. I believe that every student has the potential to be successful and cannot wait to be with you along your entire journey from enrollment to graduation at NCS. One of the best things about working at NCS is that we have a wonderful  team of staff and faculty who are devoted to the success of adult learners. I truly love my job. While not at work, I study Japanese and teach Korean.
 
2. Our Model
DUAL MODEL OF ACADEMIC ADVISING
 
The School of New and Continuing Studies (NCS) developed an advising model to better meet the needs of adult learners in hybrid and online programs. In the dual model, students have access to a faculty mentor in their major program and a professional advisor in a centralized advising office. Both faculty mentors and centralized professional advisors advise students concurrently throughout students’ tenure at the school. Supporting student success and persistence is our highest priority. NCS utilizes Starfish (student retention software) as a communication and retention-tracking tool, but high-touch advising, community-building, and responsiveness to student issues are the most effective methods of supporting student success, retention, and persistence.
 
Faculty Mentor Responsibilities
·         Promote student-faculty interaction
·         Integrate students into the major program community
·         Encourage engagement in curricular and co-curricular opportunities in the major discipline
·         Provide guidance in disciplinary and professional development
 
Professional Advisor Responsibilities
·         Guide general education planning and assist with major and minor selection
·         Connect students to campus community and opportunities
·         Provide support to and intervention for students
·         Provide accurate policy and procedure information
 
This model encourages collaboration between professional advisors and faculty, and both faculty mentors and professional advisors share the following responsibilities:
 

- Ask students to reflect on their experiences and consider their impact on their educational goals, plan and progress.

- Challenge students to strive for excellence personally and academically.

- Encourage students to take responsibility for their own learning and progress.

- Ask students to practice positive decision-making and problem-solving skills.

- Respond to student questions and concerns, presenting options and guiding their decision-making.

- Advocate for students within the department, college, and university.
 
NCS Student Responsibilities for Advising Success
·         Newly admitted degree seeking students are required to meet with BOTH their faculty mentors and professional advisors before registering for their second quarter. All new degree seeking students will have a mandatory advising hold on their record. The advising hold can only be removed by their professional advisor. 
·         Students are required to speak with a professional advisor in order to declare a new major or minor.
·         All students are expected to meet with their faculty mentor once a year.
·         All graduating seniors must meet with a professional advisor to finalize their academic plan and fill out a graduation application. Degree-seeking students will have an advising hold placed on their account the quarter after they have earned 135 credits. 
·         Students on probation must meet with a professional advisor to discuss their status and success strategies every quarter before registering for the next quarter.
 
 
3. Advising Appointment (Jack) Can we have this module sync with Suki's Outlook Calendar?
4. Advising FAQ (Suki)
1.       Is there a website with information about all the majors and certificates at NCS?
The course catalog includes degree offerings and requirements for all programs offered at NCS. http://catalog.seattleu.edu/content.php?catoid=33&navoid=2588
 
2.       When do I really register for classes?
The normal registration process works like this:  Seniors register first, followed by juniors, sophomores, and freshmen. For specific dates, visit SU Online or Academic Calendar.  The Academic Calendar includes registration dates, class start dates, add/drop deadlines, exam dates and more. https://www.seattleu.edu/redhawk-axis/academic-calendar/
 
3.       When should I meet with my advisor?
We recommend that you meet with your advisor at least once each quarter prior to registration.  But, meeting more often will allow you to get to know your advisor and feel more comfortable asking questions.   You should meet with your advisor any time you have questions or concerns that may affect your academic progress at NCS.
 
4.       How do I change my major?
You will need to submit a competed a "Change of Major" form to the college that your new major belongs to.   This form is available at (insert the form link).
 
5.       Can I get a full refund if I need to withdraw from the quarter?
There are dates set each quarter as to how much will be refunded to you should you need to withdraw from any class or classes. Please view the Academic Calendar for specific dates.
 
6.       What resources are available to me to help me be a successful student?
There is an abundance of resources to help you be a successful student at SU. You may view a listing of many resources on campus on our Student Resource webpage.
 
7.       How soon can I earn my bachelor’s degree?
For a bachelor’s degree, you must complete a minimum of 180 credits. There are four quarters a year just like the seasons. You all have entered SU with transfer credits and therefore, you may be able to speed up graduation. Please see your academic advisor to create a graduation plan.
 
 
 
[Student Handbook_DRAFT.pdf](https://github.com/suwebdev/ncs-michigan/files/945559/Student.Handbook_DRAFT.pdf)

**Student Resources:**  
1. Academic Calendar (Jack)
2. Academic Policies (Trish)
3. Forms (Suki)
Hi Sara,
 
https://seattleu.edu/redhawk-axis/forms/
 
Out of all the forms, I would say that the most commonly filed forms are:
 
·         Add a Major, Degree, Specialization, or Certificate
·         Change of Major, Degree, or Specialization
·         Drop Major, Minor, Degree, Specialization
·         Independent Study, Directed Study or Internship Request Form
·         Withdrawal Request
 
We also use a PEP form a lot, but SU does not make it available to students. Only to faculty and staff.
 
https://www.seattleu.edu/redhawk-axis/academic-policies/
 
I think NCS students should be given a link to the entire academic policies. They are all helpful, but here are my picks.
 
·         Academic Probation Dismissal Appeal UG (2005-2)
·         NCS Admissions Policy (2015-02)
·         Credit for Military Schooling (75-26)
·         Full-Time Part-Time Student Status (77-5)
·         Grade Point Average Requirements for Degree Completion (75-2)
·         Grades of Courses Acceptable for Transfer (75-5)
·         Hardship Withdrawal (2012-2)
·         Incomplete Removal (97-3)
·         Performance Criteria for NCS (2015-3)
·         Readmission (76-10)
·         Refunds of Tuition and Fees (75-9)
·         Repeated Courses (77-2)
·         Restrictions on Student Records (76-3)
·         Student Leave of Absence (2014-1)
·         Transfer Policy (77-1)
·         University Core Curriculum (2012-1)
·         Withdrawal (75-22)
 
Trish, the GPA policy for degree completion needs to include NCS --  https://www.seattleu.edu/media/redhawk-axis/registrar/registrar-policies/Degree-completion-GPA-75-02.pdf.
 
Thank you!
 
Suki
 
4. Handbook (Sara) - We would like this to be a downloadable PDF for students
5. Support Services
[Writing Center](https://www.seattleu.edu/writingcenter/)
[Tutoring Center](https://www.seattleu.edu/learning-assistance/tutoring-services/)
[Counseling Center](https://www.seattleu.edu/caps/)
[Office of Multicultural Affairs](https://www.seattleu.edu/oma/)
[Career Services Center](https://www.seattleu.edu/careerservices/)
[Veterans](http://www.seattleu.edu/veterans/)
[Student Financial Services](https://www.seattleu.edu/sfs/)
[Office of the Registrar](https://law.seattleu.edu/office-and-administration/registrar)
[IT Help Desk ](https://www.seattleu.edu/support/)
[Student Health Center](https://seattleu.edu/student-health/)
