### ISSUE TITLE
Fine-tune Course Pages

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#43]
Make these changes to course pages:

1. Remove instructors from courses (we want these to be more "catalog" listings than "section" listings)
2. Make sure we're categorizing the courses properly (that weird course search tag, etc.)
3. Show demo of how course work samples would look in Course Details
4. Show how link to sample syllabus would look in Course Details

**Comment by jfehrenbacher** [comment]
Ok so here's something I've been wondering...

Rather than creating each course within the "Courses" section of the theme, I could just make an independent page for each course. It seems like we're, for the part, just fighting the theme's LMS, and these pages could still be displayed with Essential Grid in the exact same way on each program's "Courses" page. 

The pages would be more easily customizable, and I'm not sure if any of the functionality that's made available to us through the use of the "Courses" section is actually stuff that we're interested in using. For example, we're not using, as of now, "Difficulties", "Tags", "Tracks", "Lessons", "Quizzes", "Quiz Questions", or "Reviews". We're also not interested in displaying courses' instructors, start/end dates, etc. It's possible that we have plans for some of these features that I'm unaware of and if that's the case let me know.
