### ISSUE TITLE
Populate Info Center Pages

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#55]
Build out Info Center Pages using content attached to this Issue.

Sara will upload content once it is packaged for production. Then, Jack can build out.

**Comment by jfehrenbacher** [comment]
[Info.Center.2 (1).docx](https://github.com/suwebdev/ncs-michigan/files/965303/Info.Center.2.1.docx)
[Student.Handbook_DRAFT.pdf](https://github.com/suwebdev/ncs-michigan/files/965305/Student.Handbook_DRAFT.pdf)

**Comment by jfehrenbacher** [comment]
I've currently got the [Meet Your Advisor](http://suncs.staging.wpengine.com/information-center/meet-your-advisor/), [Our Advising Model](http://suncs.staging.wpengine.com/information-center/our-advising-model/), and [Advising FAQ](http://suncs.staging.wpengine.com/information-center/advising-faq/) pages all built out. 

As I start to move on to other sections of the Information Center, I think we have a few things to clear up. I'm not sure that we have a definitive IA that includes the Admissions, Advising Center, Cost & Financial Aid, Student Resources, & Employment Opportunities sections. As far as I'm aware, we have a couple different versions of the IA that each include bits and pieces, and then several different documents that each have bits and pieces of content that are all organized differently, and I think it might be gumming up the works a bit. At least for me!

I'm going to compile the relevant information and documents that I have here and we can try to sort out our thoughts on them.

[Info.Center.docx](https://github.com/suwebdev/ncs-michigan/files/977300/Info.Center.docx)
This document from Issue #32 lays out the IA of the Advising Center and Student Resources, which are both children of the Information Center.

[Info.Center.2.docx](https://github.com/suwebdev/ncs-michigan/files/977305/Info.Center.2.docx)
This document from Issue #32  gives us a good chunk of content filling out the Advising Center, and also asks some good questions about the Student Resources section that still need to be answered.

[NCSWebsiteIA.docx](https://github.com/suwebdev/ncs-michigan/files/977326/NCSWebsiteIA.docx)
This is the complete IA from long ago that doesn't include an Advising Center and I believe is outdated in other ways as well. For example, the Student Resources section does not match the one from the Issue #32 documents, so perhaps this should be reviewed.

[Admissions.docx](https://github.com/suwebdev/ncs-michigan/files/977331/Admissions.docx)
This document contains a bulk of good content for the Admissions pages as well as Costs & Financial Aid, but is organized in a way that is a little hard to decipher, particularly because I'm not confident about the IA of said sections currently.

This is a long winded way of saying that I'm a little bit lost when it comes to the Information Center right now, which was probably inevitable as it's such an exhaustive portion of the site. I think we need to have a definitive version of the IA for the Information Center that includes all of the sections mentioned (Admissions, Advising Center, Cost & Financial Aid, Student Resources, Employment Opportunities), and also that we need to standardize how we'll be delivering content for a section that has so many moving pieces. 

Perhaps we could have just one issue open at all times where a discussion pertaining to the Information Center IA can occur? That way all relevant documents can live in one place and we're all communicating on the same page (literally, ha!)

Let me know what you guys think. I'm going to continue to build out some Student Resources pages and I will update this issue accordingly.

**Comment by jfehrenbacher** [comment]
[Student Handbook ](http://suncs.staging.wpengine.com/information-center/student-handbook/)Page

Alternatively, we could just have the link in the mega menu take you directly to the [Handbook PDF](http://suncs.staging.wpengine.com/wp-content/uploads/2017/05/Student.Handbook_DRAFT.pdf). Let me know what you think!

**Comment by reiners** [comment]
Hi Jack,
This looks awesome, though I love the idea of linking the downloadable PDF in the mega menu.
Thoughts team?
Thanks,
Sara


Sara Reiner | Director of Marketing and Communications
School of New and Continuing Studies | Seattle University
Office: (206) 296-2461
seattleu.edu/ncs

________________________________

**Comment by jfehrenbacher** [comment]
[Forms](http://suncs.staging.wpengine.com/information-center/forms/) Page

I've just added links to the forms mentioned in the [Info.Center.2.docx](https://github.com/suwebdev/ncs-michigan/files/977524/Info.Center.2.docx) document. I've also added space for a little bit of content if we need to explain why they'd need the form, or whatever else. If we don't think we need a blurb next to each link to a form that can be removed, and it can, effectively, just be a page full of teaser boxes.

**Comment by jfehrenbacher** [comment]
[Support Services](http://suncs.staging.wpengine.com/information-center/support-services/) Page

As of now this page is just a space for links to seattleu.edu pages, essentially. If we want actual content on this page describing each of these services or how to go about utilizing them that's absolutely possible, obviously. Let me know your thoughts on that.

All images are placeholders.
