### ISSUE TITLE
Update content on Student Success > Testimonials page

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#60]
Add content from #58 to the Student Success > Testimonials page.

Explore alternative presentation of testimonial that makes better use of images/text size.

**Comment by jfehrenbacher** [comment]
I've updated the [Testimonials](http://suncs.staging.wpengine.com/student-success/testimonials/) page to display the three different options that the theme gives us. Changes can be made with CSS to make things more legible if that's a problem. None of them allow for very large images, however.

I can look into alternate plugins if we'd like, or we can settle for one of these and tweak it with CSS if need be.

Let me know what you think!

**Comment by shawnr** [comment]
Feedback on current progress:

None of the existing testimonial forms are good for us. Explore presentations that use images more prominently. Include image (or mini-carousel, etc.), testimonial text, space for name, job title/company, and link to portfolio.

In top area of page leave room for some text to introduce page and add an image that will eventually be replaced with our testimonial video (so use HD video aspect ratio).

**Comment by jfehrenbacher** [comment]
Student Testimonials example at the bottom of this page. Displayed as a list rather than a carousel, with larger image, room for job title and portfolio link, and testimonial text. We could try and figure out a way to display this as a carousel but it's probably going to mean finding a third party plugin. Could potentially use Revolution Slider, though considering its loading issues and how much it can slow down a page that might not be worth it.

**Comment by jfehrenbacher** [comment]
Forget to add a link to the page:

http://suncs.staging.wpengine.com/student-success/testimonials/

**Comment by shawnr** [comment]
Spice up the display, but otherwise this is good.
